#!/usr/bin/env python3
import logging
import sys, os, re
import http.server
import socketserver
import shutil
import webbrowser
import threading
import json
import colorcet as cc
import seaborn as sns
import pypandoc as py
import zipfile
from bs4 import BeautifulSoup
from getopt import *
from tempfile import NamedTemporaryFile, TemporaryDirectory

fonts = [
    'http://fonts.googleapis.com/css?family=Raleway',
    'http://fonts.googleapis.com/css?family=Droid%20Sans',
    'http://fonts.googleapis.com/css?family=Lato',
]

base_stylesheets = [
    'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css',
]

prod_stylesheets = [
    'https://cdn.jsdelivr.net/gh/hubbl-ai/glasseye@development/glasseye/css/tufte.css',
    'https://cdn.jsdelivr.net/gh/hubbl-ai/glasseye@development/glasseye/css/GlasseyeCharts.css',
]

dev_stylesheets = [
    '{dir}/css/tufte.css',
    '{dir}/css/glasseyeCharts.css',
]

dev_scripts = [
    "{dir}/ts/dist/glasseyechart.js"
]

prod_scripts = [
    'https://cdn.jsdelivr.net/gh/hubbl-ai/glasseye@development/glasseye/ts/dist/glasseyechart.js'
]

tpl = '''<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>{title}</title>
        {fonts}
        {stylesheets}
        {scripts}
    </head>

    <body>
        <div id = "tufte_container">
            {soup}
        </div>
        <script type="text/javascript">
            {code}
        </script>
    </body>
</html>
'''

# Mode is 'dev' for development mode (with the '-D' flag), and 'prod'
# for production mode.

mode = 'prod'

module_name = 'Glasseye'
src_dir = '.'
logger = None
default_port = 7300

# Function to wrap with tags
def wrap(to_wrap, wrap_in):
    contents = to_wrap.replace_with(wrap_in)
    wrap_in.append(contents)

def resolve_color_palette(colors, n_colors, desat):
    if type(colors) == str and colors.startswith('cc.'):
        try:
            cc_palette = colors.split('.')[1]
        except Exception as exc:
            logger.fatal(f'invalid colorcet palette "{colors}"')

        colors = getattr(cc, cc_palette)
        logger.info(f'using colorcet {cc_palette} palette')

    palette = sns.color_palette(
        palette=colors, desat=desat, n_colors=n_colors)

    if palette:
        palette = [
            '#%02X%02X%02X' % tuple(
                map(
                    lambda x: int(255 * x),
                    hue
                )
            ) for hue in [c for c in palette]]
        
    return palette

class ChartDefinition:
    def __init__(self, *args, **kwargs):
        self.tag = None
        self.module_name = None
        self.module_source = None
        self.function = None
        self.optional = {}

        for k, v in kwargs.items():
            setattr(self, k, v)

        for attr in ['tag', 'module_name', 'module_source']:
            if not hasattr(self, attr):
                raise Exception('invalid function definition')

        if not self.function:
            self.function = self.tag

# Register a custom chart
def register_chart(filename, defs):
    with open(filename) as ifp:
        # Parse the file, and add it to a list of function
        # definitions.
        defn_list = json.loads(ifp.read())
        if type(defn_list) == dict:
            defn_list = [defn_list]
        for defn_dict in defn_list:
            defn = ChartDefinition(**defn_dict)
            defs.append(defn)

    return defs

# Function to add charts
def add_chart(chart_id, fields, soup, code_parts, module=module_name, function_name=None):
    all_fields = {
        'data':[],
        'size':{},
        'file':{},
        'colors':'pastel',
    }

    palette_fields = {
        'colors':'pastel',
        'n_colors':10,
        'desat':1,
    }

    if fields:
        all_fields |= fields

    if not function_name:
        function_name = chart_id
        
    for d in enumerate(soup.find_all(chart_id)):
        attrs = d[1].attrs
        args = [f"'#{chart_id}_{str(d[0])}'"]   # Insert the div ID

        # Figure out the colors

        for field, dv in palette_fields.items():
            if field in attrs:
                if field == 'colors':
                    try:
                        value = json.loads(attrs[field])
                    except Exception as exp:
                        value = attrs[field]
                        if type(value) != str:
                            raise

                    if type(value) == list and len(value) == 1 and type(value[0] == str):
                        value = value[0]

                    palette_fields['colors'] = value
                else:
                    try:
                        palette_fields[field] = json.loads(attrs[field])
                    except Exception as e:
                        logger.error(e)
            elif field in ['path', 'format']:
                try:
                    value = json.loads(attrs[field])
                except Exception as exp:
                    raise

                all_fields['file'][field] = value[field]

        # Compute the palette
        all_fields['colors'] = resolve_color_palette(**palette_fields)

        # Resolve everything but color.

        for field, dv in all_fields.items():
            try:
                if field == 'colors':
                    value = str(all_fields['colors'])
                elif field in palette_fields:
                    continue
                elif field in attrs:
                    value = attrs[field]
                else:
                    value = json.dumps(dv)

                args.append(value)
            except:
                logger.error(f'Error on chart : {chart_id}')
                raise

        code_parts.append(f"{module}.{function_name}({','.join(args)});")
        d[1].name = "span"
        d[1].contents = ""
        d[1].attrs = {}
        d[1]['id'] = chart_id + "_" + str(d[0])
        d[1]['class'] = "chart-container"
        tag = soup.new_tag("br")
        d[1].insert_after(tag)

    return code_parts

def main():
    global mode
    global logger

    filters = []
    chart_defs = []
    extras = ['--mathjax']
    title = None
    input_file = None
    output_file = None
    server_mode = False
    zip_mode = False
    port = default_port
    verbosity = logging.WARNING
    zipped_filename = ""
    errors = 0
    usage = '''Usage: glasseye args input_file
where args arg one of:
-c|--chart  file   # Add a custom chart to glasseye
-D|--dev           # Run this script in development mode
-f|--filter filter # Add a filter to be passed to pandoc
-h|--help          # Print this message
-o|--output file   # File to which to store HTML document
-p|--plot          # Short cut for adding the pandoc-plot filter
-s|--server        # Run glasseye in server mode
-t|--title         # Title for generated HTML document
-v|--verbose       # Increase debugging output. May be repeated
-z|--zip  file     # zip the output directory to file
--port             # the port to use in the url. defaults to 7300

In dev mode, the script must be run in the same folder as the script.
'''

    opts, args = getopt(
        sys.argv[1:],
        'c:D:f:o:pst:vz:',
        ('chart', 'dir', 'filter', 'output', 'plot', 'server', 'title:', 'verbose','zip=', 'port=')
    )
    
    for k, v in opts:
        if k in ['-c', '--chart']:
            chart_defs = register_chart(v, chart_defs)
        elif k in ['-D', '--dir']:
            mode = 'dev'
            global src_dir
            src_dir = os.path.abspath(v)
        elif k in ['-f', '--filter']:
            filters.append(v)
        elif k in ['-o', '--output']:
            output_file = v
        elif k in ['-p', '--plot']:
            filters.append('pandoc-plot')
        elif k in ['-s', '--server']:
            server_mode = True
        elif k in ['-t', '--title']:
            title = v
        elif k in ['-v', '--verbose']:
            verbosity -= 10
        elif k in ['-z', '--zip']:
            zipped_filename = v
            zip_mode = True
        elif k in ['--port']:
            port = int(v)
        elif k in ['-?', '-h', '--help']:
            errors += 1
        else:
            sys.stderr.write(f'invalid option {k}\n')
    
    logging.basicConfig(level=verbosity)

    logger = logging.getLogger()

    logger.info(f'running in {mode} mode')

    if len(args) != 1:
        errors += 1

    if errors:
        sys.stderr.write(usage)
        sys.exit(0)

    input_file = args[0]

    if output_file is None:
        base, ext = os.path.splitext(args[0])

        if ext != '.md':
            logger.error('file must have ".md" extension')
            errors += 1
            sys.exit(0)

        output_file = base + '.html'
    
    if os.path.exists(output_file):
        os.rename(output_file, output_file + '~')

    if title is None:
        title, _ = os.path.splitext(
            os.path.basename(output_file)
        )
        
        logger.info(f'derived title {title} from file {output_file}')

    logger.info(f'creating {output_file}')

    # Call pandoc and parse the HTML with BeautifulSoup
    output_dir = os.path.dirname(output_file)
    with NamedTemporaryFile(suffix='html', delete_on_close=False, dir=output_dir) as pfp:
        pfp.close()

        if hasattr(py, 'convert'):
            convert = py.convert
        else:
            convert = py.convert_file
        
        convert(
            input_file,
            'html',
            outputfile=pfp.name,
            extra_args=extras,
            filters=filters
        )

        with open(pfp.name, 'r') as rfp:
            pdoc = rfp.read()
            soup = BeautifulSoup(pdoc, 'html.parser')

    # Process the generated HTML to match the Tufte format

    for a in soup.find_all('marginnote'):
        p = soup.new_tag("p")
        a.replace_with(p)
        p.insert(0, a)
        a.name = "span"
        a['class'] = "marginnote"

    for a in enumerate(soup.find_all('sidenote')):
        a[1].name = "span"
        a[1]['class'] = "marginnote"
        a[1].insert(0, str(a[0]+1) + ". ")
        tag = soup.new_tag("sup")
        tag['class'] = "sidenote-number"
        tag.string = str(a[0]+1)
        a[1].insert_before(tag)

    for a in soup.find_all('checklist'):
        l = a.parent.findNext('ul')
        l['class'] = "checklist"
        a.extract()

    if soup.ol != None:
        for ol in soup.find_all('ol'):
           if ol.parent.name != 'li':
               wrap(ol, soup.new_tag("div", **{'class':'list-container'}))

    if soup.ul != None:
       for ul in soup.find_all('ul'):
           if ul.parent.name != 'li':
               wrap(ul, soup.new_tag("div", **{'class':'list-container'}))

    # Process the charts.

    code_parts = []
    code_string = ""

    # Standard charts

    standard_charts = {
        'linechart':{'curved':0},
        'piechart':{'donut':0,'continuos_rotation':0},
        'skey':{'link_color':'source-target', 'node_align':'left'},
        'barchart': {'horizontal':0},
        'tree':{'vertical':0},
        'venn':None,
        'gantt':None,
        'treemap':None,
        'heatmap': {'show_legend':0,'interp':'rgb', 'gamma':0},
        'dotplot':None,
        'scatterplot':None,
        'boxplot':None,
        'force':None,
        'chord':None,
        'disjoint':None,
        'bollinger':None,
        'dendrogram': {'view_scale_factor':1},
        'contour':None,
        'areachart':None,
        'bubblechart':{'ease_in':0,'drag_animations':0},
        'voronoi':None,
        }

    for s, args in standard_charts.items():
        add_chart(s, args, soup, code_parts)

    # Add any custom chart defs

    for defn in chart_defs:
        add_chart(defn.tag, defn.optional, soup, code_parts, defn.module_name, defn.function)
        logger.info(f"Added custom chart {defn.tag}")

    # We use the same indentation as the template for the script

    code_string = '''
            '''.join(code_parts)

    # Account for Apple's tendency to be a nanny

    code_string = re.sub('[“”]', '"', code_string)
    code_string = re.sub("[“’‘”]", "'", code_string)

    # Construct the mode-specificities
    scripts = []
    stylesheets = base_stylesheets

    if mode == 'dev':
        scripts = scripts + [path.format(dir=src_dir) for path in dev_scripts] if not server_mode else scripts + [f"ts/dist/{os.path.basename(path)}" for path in dev_scripts]
        stylesheets = stylesheets + [path.format(dir=src_dir) for path in dev_stylesheets] if not server_mode else stylesheets + [f"css/{os.path.basename(path)}" for path in dev_stylesheets]
    else:
        scripts = scripts + prod_scripts
        stylesheets = stylesheets + prod_stylesheets

    for src in set([defn.module_source for defn in chart_defs]):
        scripts.append(src)


    # Put it all together into a set of arguments for turning the template
    # into the finished document.

    tpl_args = {
        'title': title,
        'fonts': "\n        ".join([
            f"<link href='{font}' rel='stylesheet' type='text/css'>" for font in fonts
        ]),
        'scripts': "\n        ".join(
            [f'<script src="{script}"></script>' for script in scripts]
        ),
        'stylesheets': "\n        ".join(
            f'<link rel="stylesheet" href="{sheet}" />' for sheet in stylesheets
        ),
        'soup': str(soup),
        'code': code_string
    }

    doc = tpl.format(**tpl_args)

    with open(output_file, 'w') as ofp:
        ofp.write(doc)

    if server_mode or zip_mode:
        with TemporaryDirectory(prefix='glasseye') as server_dir_name:
            copy_data(output_file, output_dir or ".", server_dir_name)
            if server_mode:
                start_http_server(server_dir_name, port)
            elif zip_mode:
                zip_directory(server_dir_name,zipped_filename)

        # Once the server exits or the zipped folder with output, the temp directory is automatically deleted.

def start_http_server(directory, port=default_port):
    if not os.path.isdir(directory):
        raise ValueError(f"Invalid directory: {directory}")

    os.chdir(directory)
    handler = http.server.SimpleHTTPRequestHandler
    url = f"http://localhost:{port}"

    with socketserver.TCPServer(("", port), handler) as httpd:
        def open_browser():
            webbrowser.open(url)

        threading.Thread(target=open_browser, daemon=True).start()

        try:
            logger.info(f"Serving {directory} at {url}")
            httpd.serve_forever()
        except KeyboardInterrupt:
            logger.info("\nServer terminated.")


def zip_directory(folder_path, output_zip):
    with zipfile.ZipFile(output_zip, 'w', zipfile.ZIP_DEFLATED) as zipf:
        for root, _, files in os.walk(folder_path):
            for file in files:
                file_path = os.path.join(root, file)
                arcname = os.path.relpath(file_path, start=folder_path)
                zipf.write(file_path, arcname)
    logger.info(f"Zipped '{folder_path}' to '{output_zip}'")

def copy_data(output_file, output_dir, server_dir_path):
    if not os.path.isdir(output_dir):
        raise ValueError(f"Source directory does not exist: {output_dir}")

    shutil.copytree(output_dir, server_dir_path,
        dirs_exist_ok=True,
        ignore=shutil.ignore_patterns('.?*')
    )

    if mode == 'dev':
        styles_and_scripts = dev_scripts + dev_stylesheets
        styles_and_scripts = [path.format(dir=src_dir) for path in styles_and_scripts]
        for sas in styles_and_scripts:
            if os.path.isfile(sas):
                filename = os.path.basename(sas)
                file_extension = os.path.splitext(filename)[-1]
                dest_dict = os.path.join(server_dir_path, "css" if file_extension==".css" else "ts/dist")
                if not os.path.isdir(dest_dict):
                    os.makedirs(dest_dict, exist_ok=True)
                shutil.copy2(sas,dest_dict)
                logger.info(f"Copied : {sas} to {dest_dict}")
    
    # rename the generated .html file to index.html

    extension = os.path.splitext(output_file)[-1] 
    new_filename = "index" + extension  
    old_filepath = os.path.join(server_dir_path, output_file)
    new_filepath = os.path.join(server_dir_path, new_filename)

    os.rename(old_filepath, new_filepath)

if __name__ == '__main__':
    main()
